### ISSUE TITLE
add a `curvenote deploy --ci` option or similar

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#106]
Motivation here is our `github` action which currently takes a long time to complete - a big part of that is the curvespace clone step, and npm install in the `_build` folder which is not necessary. 

When deploying on ci:

 - we should just process the content to produce the deployable assets in `_build/web/app/content` and then deploy that folder
 - exit(-1) on errors in this mode on failure, if not across the board on failure

**Comment by rowanc1** [comment]
I have picked up a few exit(-1) in #116. You can usually just `throw new Error()` and that will be put on the console in red. I was doing `log.error` which isn't quite as good.

**Comment by stevejpurves** [comment]
we now have a `curvenote build --ci` so maybe only a small change is needed to add that to `curvenote deploy --ci` and then the options pass through to the build code?
