### ISSUE TITLE
Provide fallbacks for index/readme and just pick a file to nominate for the root

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#119]
Running through the latest curvenote init to put docs together... so I had a little example site with content like this:
```
blog/
	logo.svg
	welcome.md
	my-first-post.md
	my-first.notebook.ipynb
```
And hit this:
![image](https://user-images.githubusercontent.com/913249/170478080-3651e61e-5854-4b75-b51c-4a12a607f7f8.png)

**Comment by stevejpurves** [comment]
here is the current sidebar in the docs for this, happy to do this differently as needed, as we can update the docs

![image](https://user-images.githubusercontent.com/1473646/170479937-4f18d7af-5e48-4cca-aeef-0a367b97df3f.png)

**Comment by stevejpurves** [comment]
Just hit this on a demo this afternoon as the folder was full of notebooks only

**Comment by stevejpurves** [comment]
Plus without this change, launchpad will also fail
