### ISSUE TITLE
validate config on load

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#122]
The types need to be respected and we should warn on any unrecognized keys.

See `validateConfig` in `config/index.ts`

example:
- [ ] you have misnamed site in the yml, and the error you get is that you don't have a curvenote.yml

**Comment by fwkoch** [comment]
Config is now validated on load with sensible error messages. Further small improvements are tracked here: https://github.com/curvenote/curvenotejs/issues/142
