### ISSUE TITLE
Define `kind` on page

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#141]
Currently, we don't know whether a particular page is an article or a notebook, when we render them in curvespace.
So for example if we want to treat notebooks differently and render a Jupyter icon, or enable download, we can't adapt.

We should save a kind to the page. `kind=Article` or `kind=Notebook`. This should be on the top or the json.

**Comment by fwkoch** [comment]
A few updates:
- Make sure this gets set on local pages
- Add it to mdast only, don't set as frontmatter on the page (not really something the user can change)
