### ISSUE TITLE
Write _toc.yml from auto-generated TOC

### ISSUE THREAD

**Issue by fwkoch** [curvenote/curvenotejs#150]
If no _toc.yml exists, curvenotejs will auto-generate toc from folder structure. If users want to make small tweaks though, they have to edit folders/files (and there's no way to get around, like, alphanumeric page ordering).

It would be useful to have a CLI command to generate a toc which can then be edited by the user.

**Comment by rowanc1** [comment]
Do you have an idea of what this command is?

Some prior art here:
https://jupyterbook.org/en/stable/structure/toc.html#generate-a-table-of-contents-from-content-files
