### ISSUE TITLE
Recognize `kernelspec` and `jupytext` frontmatter

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#162]
If these are present, the markdown file is actually of kind notebook (see #141)

![image](https://user-images.githubusercontent.com/913249/173459494-73a21491-fee6-47e2-afb8-4ccea9478429.png)

There should also be a pass to set any code-cell directives without langauge defined to the kernelspec.language.

This property is also sometimes nested under jupyter.kernelspec (which can be a transparent fallback).

**Comment by stevejpurves** [comment]
for context see: https://jupyterbook.org/en/stable/file-types/myst-notebooks.html
