### ISSUE TITLE
Transformation for links to internal files.

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#176]
* update the slugs
* if it is a static file, move it to static and update the path.
  * this will need some fixes for the CDN deployment.

**Comment by stevejpurves** [comment]
more context - this is internal files in terms of files references in markdown or the ipynb content?

**Comment by rowanc1** [comment]
A lot of the repos have file links, and they are all broken and/or open a new page as they are treated as external.

There is a link pass on msast that we can add this to, yeah.
