### ISSUE TITLE
Add data-canonical-src to images to maintain their original source

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#180]
I also kinda like the "camo" subdomain that github has. :)

![image](https://user-images.githubusercontent.com/913249/173683350-1576fbc2-099e-4757-95d0-b6529e57f46b.png)

**Comment by stevejpurves** [comment]
will this only work for external images?
in which cases should we be adding this?

**Comment by rowanc1** [comment]
All images are copied to local now. But they loose their original url, this keeps it available. Very much a nice to have and low priority, but can pick it up in an image pass when we do widths, etc.
