### ISSUE TITLE
Jupyter shouldn't invert in dark mode

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#222]
![image](https://user-images.githubusercontent.com/913249/175222980-8acba831-2e29-44c6-84da-de5ed61df7ce.png)

**Comment by stevejpurves** [comment]
I couldn't get it to go to grayscale on dark and non inverted is unreadible.
Maybe we need to put a background on ?? 🤔

**Comment by stevejpurves** [comment]
![Image](https://user-images.githubusercontent.com/1473646/175308690-e14e38d0-7c34-4931-8242-63beee1c6ff2.png)
