### ISSUE TITLE
Notebooks don't link properly

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#54]
During web builds, `curvenotejs` reconciles links to other articles in a project, converting the `oxa:` link to a correct relative link for the build.

For some reason, this is not happening for notebooks, but should work.,

An example is here https://stevejpurves.curve.space/la-palma-earthquakes/notebooks but this can be recreated with any curvenote project, by including an article and notebook and in the article adding  a cross-reference to the notebook using `[[nb:`

**Comment by fwkoch** [comment]
@stevejpurves / @rowanc1 - is this one resolved? Didn't have any trouble linking notebooks (and the issue is pretty old).

**Comment by rowanc1** [comment]
Could be!
Let's close and come back to it if it remains an issue. I haven't seen it recently.
