### ISSUE TITLE
Notebooks render html in markdown cells (safely with limited schema?)

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#55]
Currently in web builds we do nothing to handle html-in-markdown properly for notebooks, meaning that we end up rendering HTML source as plain text content.

It is common for notebook authors to use HTML in markdown cells to achieve things like this:

![image](https://user-images.githubusercontent.com/1473646/162419363-5d04697f-e491-43e0-ab6d-b8521d8839f9.png)

example notebook: https://github.com/gimli-org/transform2021/blob/main/1_Creating_a_subsurface_model.ipynb

Which currently renders in curvenote (and curvespace) as:

![image](https://user-images.githubusercontent.com/1473646/162419498-614f301b-2859-4b0d-8c01-75cdfebcf165.png)

## Objective

Modify notebook processing during the web build process to handle HTML in markdown cells. 

The `processNotebook` function is where the specialised processing for notebooks happens at the moment. https://github.com/curvenote/curvenotejs/blob/feat/web/src/web/cache.ts#L46

When content/markdown cells are encountered we should process these (using schema/mdast) to sanitize (<script> removal) render the HTML appropriately.

**Note:** rendering images included in HTML, both local and via URL should be handled here 👉🏻 https://github.com/curvenote/curvenotejs/issues/56

**Comment by rowanc1** [comment]
Initial pass is complete!

🚀
