### ISSUE TITLE
Notebooks - follow links in markdown cells for local images

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#56]
Currently during web builds, we do nothing to find and process local images that may be referenced in a markdown cell in a jupyter notebook.

We should start doing that when:
* the image included in available on a url
* the image included is available to us on disk relative to the notebook

Also, images can be referenced:
* in markdown syntax `![curvenote logo](./curvenote.png)`
* using an HTML `<img />` tag - (see also https://github.com/curvenote/curvenotejs/issues/55)

All these scenarios should be supported.

Currently, it seems in some cases that the build process correctly constructs links to local images when specified in markdown but the images are never made available in the `public` folder. e.g. https://transform.softwareunderground.org/2021-practical-python/t21-practical-seismic-with-python

**Note:** currently when we add notebooks to curvenote.com, images are lost :( we need more work on version control to fix that, so for this issue we have to manually make available and *locally referenced image* in order to test.

**Comment by rowanc1** [comment]
🚀
