### ISSUE TITLE
links with underscores get escaped and broken

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#61]
when we have a link with underscores, these seem to get escaped in `myst` 

![image](https://user-images.githubusercontent.com/1473646/164649208-2267456b-4a1a-45a2-92d0-79275e48fdd1.png)

and then those backslashes get escaped (URL encoded) again when curvespace is built leading to a broken link

![image](https://user-images.githubusercontent.com/1473646/164649381-4e2316cc-b113-4e31-8236-e9498d031703.png)

**Comment by fwkoch** [comment]
I couldn't recreate this one. I tried (1) links with underscores in a md file from github and (2) links with underscores pulled directly from curvenote, and both seemed to work fine?

Let me know if your example came in a different way or if there's something else going on.

**Comment by stevejpurves** [comment]
@fwkoch try pulling from this project? https://curvenote.com/@swung/transform-2022-getting-started-in-python/overview

I tried this again last night and still got the issue - if you can't reproduce we can pair up and take a look at what is happening on my machine

**Comment by fwkoch** [comment]
Tracked this down to a recent change in `prosemirror-markdown`: https://github.com/ProseMirror/prosemirror-markdown/commit/88776bd5623b5186c26775ad5947ffde75db5f27

Bumping the dependency in schema - https://github.com/curvenote/schema/pull/57 - and consuming that change in curvenotejs should resolve this.

**Comment by fwkoch** [comment]
URLs are still getting escaped though, this just changes the escaping functionality. If there are other cases where escaping is a problem, it could need an additional fix.

**Comment by rowanc1** [comment]
Schema has been bumped to `0.12.3`.

I think we should close this for now and see if it comes up again down the road. :)

Nice work tracking this down!

**Comment by stevejpurves** [comment]
Yep, this one was well down in the weeds! 👏🏼  @fwkoch
