### ISSUE TITLE
Cannot Find Image

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenotejs#76]
Cannot find image, when it is a base64 image.

We should write this to the correct file.

![image](https://user-images.githubusercontent.com/913249/165146484-f2cfa1c0-de3d-41f2-bf02-11ebd04248e4.png)

**Comment by stevejpurves** [comment]
not sure if this overlaps with https://github.com/curvenote/nbtx/issues/4

**Comment by fwkoch** [comment]
nbtx handles base64-encoded jupyter outputs. However, this doesn't support other base64 strings in `image` MyST nodes, e.g. using `data:` URIs in markdown that looks like:
```
![](data:image/png;base64,iVBORw0KGgo...)
```
