### ISSUE TITLE
Tables with images don't render on curvespace

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#83]
a curvenote article with a table containing 2 images:

![image](https://user-images.githubusercontent.com/1473646/165295881-50fae45c-750f-433f-a1b5-2d62e20afbaf.png)

produces a model like this:

![image](https://user-images.githubusercontent.com/1473646/165296008-50921756-599f-4ec9-81e1-b15da0789257.png)

that does not render on a curvespace site

![image](https://user-images.githubusercontent.com/1473646/165296075-449e468b-dc7d-4b76-9684-0bc1c60c7bd1.png)

**Comment by stevejpurves** [comment]
Note I just re-tested this using the latest curveotejs/curvespace from this morning and it's the same

**Comment by stevejpurves** [comment]
note that this table (with 2 rows?) does work 
![image](https://user-images.githubusercontent.com/1473646/165318139-e16a4ef1-5a89-4bd3-9409-3fc592fb68f5.png)


https://curvenote.com/@stevejpurves/blog/the

**Comment by rowanc1** [comment]
@stevejpurves this is actually because of the multiple enters that I think you put in there to center one image. One enter is ok, two are not.

I have fixed up the sponsor page and this can be repulled. and should work.

This is a schema serialization thing we should fix @fwkoch.

**Comment by stevejpurves** [comment]
ok will pul the content again.

> This is a schema serialization thing we should fix @fwkoch.
do we have an issue for this ☝🏼 @fwkoch

**Comment by fwkoch** [comment]
I fixed this in markdown rendering by just looking at the start of each table row, and if it's a paragraph with text with leading newlines, reduce to a single newline. It feels... not super robust, but gets the job done for this example at least.

**Comment by fwkoch** [comment]
Ok - now we deal with (1) leading newlines and (2) empty paragraph nodes. Formatting is lost, but the table now renders: 
![image](https://user-images.githubusercontent.com/9453731/166554547-a76adfc6-a62d-4f1f-a4fa-83e4ac6f2ce6.png)
