### ISSUE TITLE
`curvenote start` watch should react to `_config.yml` changes

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenotejs#84]
currently you need to restart the server (it is nice there is a message to that effect though)

**Comment by rowanc1** [comment]
This is about marking all files in a project as dirty, hard at the moment, but shouldn't be when @fwkoch is moving things into state!

**Comment by rowanc1** [comment]
This is about marking all files in a project as dirty, hard at the moment, but shouldn't be when @fwkoch is moving things into state!

**Comment by stevejpurves** [comment]
so will potentially be picked up in https://github.com/curvenote/platform/issues/1307

**Comment by stevejpurves** [comment]
superceeded
