### ISSUE TITLE
curvenote.yml has `project` section with project frontmatter, toc customization options

### ISSUE THREAD

**Issue by fwkoch** [curvenote/curvenotejs#94]
![image](https://user-images.githubusercontent.com/9453731/166409596-745e4578-ebc8-48a1-88d0-a3b43548ac87.png)

The `project` portion of `curvenote.yml` is entirely independent of curve.space site configuration. It includes project frontmatter as well as options for generating the toc from the project folder (or a reference to an explicit toc).

**Comment by stevejpurves** [comment]
we can close this one? @fwkoch
